### ISSUE TITLE
3. FE Home Page

### ISSUE THREAD

**Issue by FrazierLE** [Capstone-Bookworm/bookworm-fe#4]
- [x] As a user, when I land on the home page, I should see all books that are available to be swapped, a search form, and a nav bar
- [x] As a user, when I click a book, I should see the details page -- adding glide feature
Limit books to 5

Acceptance Criteria
- [x] It should query all books
- [x] It should have a search bar which will be a fetch call to backend with button click
- [x] Should be able to click on a book and be routed to details page - fetch book details

**Comment by Adelle-Pitsas** [comment]
Just in the demo I saw that books that are currently checked out still show up on the home page. My understanding of this is that the home page only shows available books

**Comment by FrazierLE** [comment]
Oh that's a good point. I was wondering about that. I was thinking we'd give the user an option of choosing a borrower if it's available and if it was unavailable, we display a message that says if it's unavailable
